### ISSUE TITLE
Intranet - R Trim analysis tool - species list to change

### ISSUE THREAD

**Issue by magdziarek** [biodiversitydata-se/biocollect#141]
There's a species list behind it - change URL, it still points to lists.**bioatlas**.se
Also change the list where eurolist birds is required, the one we had before now doesn't have species between 504 and 699. I had to remove them because they are not supposed to be used by surveyors when entering data. So we have two lists - one full eurolist birds (https://lists.biodiversitydata.se/speciesListItem/list/dr627) to be used in TRIM analysis and one shorter (https://lists.biodiversitydata.se/speciesListItem/list/dr158) to be used in BioCollect autocomplete species field.

#140
https://github.com/biodiversitydata-se/biocollect/issues/140

**Comment by mathieuLU** [comment]
i don't get everything here. What file are you talking about, when you say that it still points to lists.bioatlas.se ?
The rtrim app is pointing to the new list module, but I guess you're talking about something else.
So now it means that the SFT people have to deal with 2 lists right ?

i took some time to try it with my shiny app. It revealed a new bug that I fixed. And another problem : the list can't be private. I changed yours, because I need the WS to work
But maybe you wanted it to be private. Please tell me if you need it private, because I would have to find another way to work with it...

**Comment by mathieuLU** [comment]
Now I have another problem with your new list. And I finally discovered why it broke my script.
All the lists we use have 2 fields, name and scientific Name, quite confusing :
In "name" we store the scientifc Name without the athor. In scientificName we store the full name + the authorship
example from dr158 (the old one) : 
name : Sylvia undata
scientificName : Sylvia undata (Boddaert, 1783)

It's the same in all our lists.
But in your new list name=scientificName

Could you fix your list please ? It seems that I can't reindex from the lists module... I guess it's an option when you create it on the first place

**Comment by magdziarek** [comment]
> i don't get everything here. What file are you talking about, when you say that it still points to lists.bioatlas.se ?

Sorry, I 'm not sure where this was. We looked at the app with Åke and we saw a link to bioatlas.se there -> I guess maybe it was just some sort of documentation inside the app?

> So now it means that the SFT people have to deal with 2 lists right ?

yes! one is behind the survey form and the other one behind the rtrim app

**Comment by magdziarek** [comment]
I think it's done now if I understood the problem correctly. Please check and close the issue if it works. 
The list to connect to RTrim is now the dr627: 
https://lists.biodiversitydata.se/speciesListItem/list/dr627

**Comment by mathieuLU** [comment]
Great it works !
