### ISSUE TITLE
Apparently possible to report time in wrong format

### ISSUE THREAD

**Issue by ekol-ali** [biodiversitydata-se/biocollect#197]
When extracting data from vinterpunktrutter with the Intranet-funktion, I noticed that one person (840410-1) managed to get time into BioCollect in the wrong format: "900" instead of the requiered "09:00".

In all three cases it was for the recent winter, so the info must have been added into BioCollect by himself. I have corrected it now, but I would have assumed it was impossible to store data in the wrong format.

**Comment by mathieuLU** [comment]
do you remember which  survey it was ? do you think it could come from the excel script ?
i could investigate if you give me more details on these surveys ;-)

**Comment by ekol-ali** [comment]
I found it in the Excel-export, but the problem was already there in BioCollect. It was in these three surveys (but already corrected by me):

https://biocollect.biodiversitydata.se/sft/bioActivity/index/85967edf-d4e7-4f24-9b62-851de0b651ce
https://biocollect.biodiversitydata.se/sft/bioActivity/index/0b63375d-8e02-4bcd-9391-60b8547d1bfa
https://biocollect.biodiversitydata.se/sft/bioActivity/index/f9a87c90-3d7b-4da2-8965-0381e12b4c52

I think they all were added by the observer directly into BioCollect

**Comment by mathieuLU** [comment]
so it does not come from the excel script. Impossible for me to write a time like that in that field. User can be so creative and unpredictable, how did he do that ? !
Or maybe it was possible at that time and fixed since then ? ("dateCreated" : ISODate("2021-10-20T07:24:46.107Z"))

If you are able to do something like that, please tell me how. If not, I think we should close the case

![Screenshot from 2022-01-20 09-42-57](https://user-images.githubusercontent.com/50901365/150303984-4c076523-e9d0-4ac4-9451-168a31be56e9.png)

**Comment by ekol-ali** [comment]
I haven't tried, but if you can't manage to recreate the problem, let's close the issue!
