### ISSUE TITLE
Species reported twice in point count - should not be allowed

### ISSUE THREAD

**Issue by ekol-ali** [biodiversitydata-se/biocollect#200]
https://biocollect.biodiversitydata.se/sft/bioActivity/index/a58361e2-bf17-3809-7c8c-c99c29871461

In this survey, "Gärdsmyg" (art 181) was reported twice. The origin is in the Excel-file sent in by the surveyor. I can find the error there. Thus, it was not reported directly in BioCollect.

I have not yet corrected it, because I thought MB wanted to see it first. The line with art=181 and 7 birds in 6 points should be art=182 (dubbeltrast). **Please correct the species number when you have looked at the case**.  

It would be good if such doublets were discovered in the import function and warned about.

**Comment by mathieuLU** [comment]
OK Thanks Åke.
I have edited the survey as well to put dubbeltrast i stället för Gärdsmyg

I will fix the excel file to add that check .
 
"excelFile" : "Som21-510524-1-#03.xlsx"

**Comment by mathieuLU** [comment]
fixed ! please have a look to what it looks like now :

**[2022-01-21 13:40:45] ERROR : The species number 181, line#169, has already been found in the file at line#168. Doublon !**

please ignore this message in the screenshot : 
[2022-01-21 13:40:45] ERROR : Filename site id (510524-1-02) and site id in the file (510524-1-03) don't match 
it's because I changed the filename to allow it to be added and pass the sitename control :)

![Screenshot from 2022-01-21 14-40-48](https://user-images.githubusercontent.com/50901365/150537041-f83eb0c4-c6b8-48bb-a046-7f7644158d43.png)

**Comment by mathieuLU** [comment]
haha and suddenly I got an email from Martin saying that he couldn't import a survey that contained 722P and 722T, because of a doublon problem :D 

Now I fixed, so that it works both for you and him, even with species with xxxP or xxxT

**Comment by ekol-ali** [comment]
Good - let me know if I should close this issue - or if you do it!
