### ISSUE TITLE
wrong total for mammals count in Nattrutterna

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/biocollect#220]
example
https://biocollect.biodiversitydata.se/sft/bioActivity/index/4a38d79a-afa9-4aeb-a404-2a7f27601432

![pastedImage](https://user-images.githubusercontent.com/50901365/159887803-baf0c40d-a8ca-41a1-9bb9-ae5e366a873c.png)

**Comment by mathieuLU** [comment]
fixed !
as expected, it was a copy-paste error in the template of the nattrutter....

`
          "dataType": "number",
          "name": "totalP13",
          "decimalPlaces": 0,
          "computed": {
            "expression": "countNonZeroValuesInColumn(**mammalObservations**, \"P13\")"
`

it was written observations instead of mammalObservations, for all the points and the total => the total line for mammals was then the same as the number of birds :)

Now I must check how many existing surveyx are wrong, and how to fix them....

**Comment by ekol-ali** [comment]
Tack Mathieu,

för alla goda insatser!

Åke

Från: mathieuLU ***@***.***>
Skickat: Thursday, 24 March 2022 16:54
Till: biodiversitydata-se/biocollect ***@***.***>
Kopia: Åke Lindström ***@***.***>; Assign ***@***.***>
Ämne: Re: [biodiversitydata-se/biocollect] wrong total for mammals count in Nattrutterna (Issue #220)


fixed !
as expected, it was a copy-paste error in the template of the nattrutter....

"dataType": "number", "name": "totalP13", "decimalPlaces": 0, "computed": { "expression": "countNonZeroValuesInColumn(**mammalObservations**, \"P13\")"

it was written observations instead of mammalObservations, for all the points and the total => the total line for mammals was then the same as the number of birds :)

Now I must check how many existing surveyx are wrong, and how to fix them....

**Comment by mathieuLU** [comment]
Actually the old protocols are fixed as well by that modification !
If we compare with the very first screenshot of this issue, we now have :
![Screenshot from 2022-03-25 09-37-44](https://user-images.githubusercontent.com/50901365/160085140-8d374829-ec40-4a88-8044-2f7037857133.png)

But in the database that total-line data is stored (but why ?). Not a big deal since this elements are not used anyway.
A way to fix these lines could be to re-save them?
no urgent at all
