### ISSUE TITLE
Invalid dates in Nattrutt for unknown reasons

### ISSUE THREAD

**Issue by ekol-ali** [biodiversitydata-se/biocollect#237]
When I look at the surveys for nattrutt 16GNO, there are three surveys (from one person) which says "invalid date" when I get them listed here:  https://biocollect.biodiversitydata.se/sft/project/index/d0b2f329-c394-464b-b5ab-e1e205585a7c

But I see no reason why!

https://biocollect.biodiversitydata.se/sft/bioActivity/index/4cc9b6a6-723c-4513-a7bb-1cb611fc8f4f?returnTo=%2Fsft%2Fproject%2Findex%2Fd0b2f329-c394-464b-b5ab-e1e205585a7c

https://biocollect.biodiversitydata.se/sft/bioActivity/edit/b4f53c20-9c0b-9f31-9df7-192463af4f27?returnTo=%2Fsft%2Fproject%2Findex%2Fd0b2f329-c394-464b-b5ab-e1e205585a7c

https://biocollect.biodiversitydata.se/sft/bioActivity/edit/81e534e9-1d34-7c4f-7343-51adf39e5257?returnTo=%2Fsft%2Fproject%2Findex%2Fd0b2f329-c394-464b-b5ab-e1e205585a7c

The date in the first post above I did remove completely and re-entered, which apparently didn't change anything (unless there is a timelag...). I also notice that the one from 2022 was entered in BioCollect (it seems) and the one from 2021 was not.

OBS! When extracted to Excel through Intranet, the "invalid dates" **seem** OK (!?)

**Comment by ekol-ali** [comment]
After a few more hours in BioCollect I encountered several more "Invalid dates" as described above. Maybe this needs to be looked at more systematically?

**Comment by mathieuLU** [comment]
here is what happened here :

![Screenshot from 2023-03-06 09-57-03](https://user-images.githubusercontent.com/50901365/223063262-0f88ae54-2bc5-4ae8-8385-3f8d918d9889.png)
we can see here several rows with "invalid date"

all of these ones do not have any records. They are events without observations. In excel you only have the line art = 000/998
![Screenshot from 2023-03-06 09-58-33](https://user-images.githubusercontent.com/50901365/223063671-b717ccad-5b97-4d03-9dba-e20fb034a891.png)

for some reason, Biocollect is using a record date in that page. Instead of using the eventDate

we have discovered this with Fredrik a couple of months back, here is the issue => https://github.com/biodiversitydata-se/biocollect/issues/175

Maybe we should put a higher priority on that one ?

**Comment by ekol-ali** [comment]
Ah, OK, then I understand. Night routes in Norrland can sometimes be empty (NEVER happens in Skåne).
If you solved it for IWC, please do the same here.
However, the highest priority of recent issues is, for me, the filters to add when putting in time stamps for the nattrutter points.

**Comment by mathieuLU** [comment]
You mentionned this problem because you thought it could create problem in the excel extract. But it's not the case. So i close this issue and keep only the one already created.
=> https://github.com/biodiversitydata-se/biocollect/issues/175 (updated today)

**Comment by mathieuLU** [comment]
fixed !

![Screenshot from 2023-03-11 14-31-34](https://user-images.githubusercontent.com/50901365/224487992-de5171e7-ff68-4dac-b24c-ab6910e8ba3e.png)

**Comment by ekol-ali** [comment]
Excellent!
