### ISSUE TITLE
Two mysterious time stamps (clock times) in Nattrutter

### ISSUE THREAD

**Issue by ekol-ali** [biodiversitydata-se/biocollect#238]
https://biocollect.biodiversitydata.se/sft/bioActivity/edit/837e2215-7085-438d-bced-5e829794f8e8?returnTo=%2Fsft%2Fproject%2Findex%2Fd0b2f329-c394-464b-b5ab-e1e205585a7c

This survey contains two very strange time stamps for P8 and P9. When looking at them in BioCollect they look OK, i.e. "1841" and "1852". But when I extract them through Intranet to an excel-file, they become "18410" and "18520". 

I have twice now deleted the 1841 and 1852 and entered them again, but the same thing happens! 

It should be noted that other changes I have made with erroneous time stamps get corrected "immediately".

**Comment by mathieuLU** [comment]
i don't have this at all in my extract !

2022 | approved | 0 | 0 | P | 1738 | 1746 | 1753 | 1803 | 1815 | 1823 | 1832 | 1841 | 1852 | 1901 | 1912 | 1920 | 1929 | 1937 | 1946 | 2000 | 2008 | 2019 | 2028 | 2040 |   |   | 837e2215-7085-438d-bced-5e829794f8e8
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
![Screenshot from 2023-03-06 11-46-33](https://user-images.githubusercontent.com/50901365/223088897-b89a32fd-ed61-4795-a043-00a192115cb7.png)

any screenshot of yours ? or please email me the file ! (zipped if possible)

**Comment by ekol-ali** [comment]
Now padel,

More this afternoon

Från: mathieuLU ***@***.***>
Skickat: Monday, 6 March 2023 11:47
Till: biodiversitydata-se/biocollect ***@***.***>
Kopia: Åke Lindström ***@***.***>; Assign ***@***.***>
Ämne: Re: [biodiversitydata-se/biocollect] Two mysterious time stamps (clock times) in Nattrutter (Issue #238)


i don't have this at all in my extract !
2022

approved

0

0

P

1738

1746

1753

1803

1815

1823

1832

1841

1852

1901

1912

1920

1929

1937

1946

2000

2008

2019

2028

2040





837e2215-7085-438d-bced-5e829794f8e8

[Screenshot from 2023-03-06 11-46-33]<https://user-images.githubusercontent.com/50901365/223088897-b89a32fd-ed61-4795-a043-00a192115cb7.png>


any screenshot of yours ? or please email me the file ! (zipped if possible)

**Comment by mathieuLU** [comment]
ok so first : 
you above sent the link to the activity 837e2215-7085-438d-bced-5e829794f8e8, but actually it was cd2eedb7-ff7e-4e7b-9f9b-495a392bc467
that's why i couldn't see the problem in the first place :) And yes i had the same problem in my file

then i went to biocollect to edit it => https://biocollect.biodiversitydata.se/sft/bioActivity/index/cd2eedb7-ff7e-4e7b-9f9b-495a392bc467
i edited it, saved, and it's now ok :)
really strange that it did not work when you edited it. Maybe Johan is right with this cache stuff

i downloaded the excel file right after and it's ok as well

**Comment by ekol-ali** [comment]
Oups, sorry about the wrong link!
It's OK here too now!
