### ISSUE TITLE
Doubles of both surveys and single rows in Nattrutter

### ISSUE THREAD

**Issue by ekol-ali** [biodiversitydata-se/biocollect#240]
[Dubbletter i nattrutter.xlsx](https://github.com/biodiversitydata-se/biocollect/files/10898964/Dubbletter.i.nattrutter.xlsx)

While going through the Nattrutter extract I find three doubles. They can be found in the attached fil. 

There are two FULL surveys in double and in one survey there is one row double. In the latter case I have contacted the surveyor.

I had hoped that the system would not allow doubles, neither single rows nor full surveys. It **seems** as if 04ENO 220615 has been imported from Excel both times (owner Mathieu Blanchet) and 18GSO 220313 has been entered in BioCollect both times (owner Surveyor).

I have removed the doubles in the file I send to Johan B for the SQL-server, but left them in BioCollect. The latter may be better for your detective work? Please remove the double surveys when you're done. 

The single row double I can fix when I hear from the surveyor.

**Comment by ekol-ali** [comment]
I already heard from the surveyor so the double row is fixed.
FYI: There were two rows of rådjur on the points, on 10FNO period 2. The lines are now lumped.

**Comment by mathieuLU** [comment]
ok i understand why. Quite sad :
![Screenshot from 2023-03-06 16-26-58](https://user-images.githubusercontent.com/50901365/223154518-9e4e88a1-ef7d-4ab8-aeb1-c559e6fc5c61.png)

Problem that occurs only with this specific error (space in the name format)

i fixed the script, my bad.

Shall i remove the doublons from the database ?

**Comment by ekol-ali** [comment]
OK, but I don't really understand how 04ENO could end up as double.
Should be two complete survey doubles - the one you handled (04ENO) and then 18GSO 220313. Could you find the problem for 18GSO? Was it the same problem?
Yes, please remove dublons.

**Comment by mathieuLU** [comment]
here is a recap :

first, from the excel files, i found **3 duplicates** : 
![Screenshot from 2023-03-07 08-06-15](https://user-images.githubusercontent.com/50901365/223349013-cf52bc30-217b-4340-91ea-c4d0a3bd0332.png)

**duplicate 04ENO-3-2022**
due to the intranet script 
i removed the activity/output/record for activityId:"49ec772c-c437-22af-4ae9-43ec03af2839"

**18GSO-1-2022**
created by the same user, at 2 different dates 
1)
	"dateCreated" : ISODate("2022-11-03T08:09:09.835Z"),
	"lastUpdated" : ISODate("2022-11-03T09:20:58.063Z"),
	"activityId" : "837e2215-7085-438d-bced-5e829794f8e8",
	"userId" : "26",

2)
	"dateCreated" : ISODate("2022-03-28T08:13:39.596Z"),
	"lastUpdated" : ISODate("2022-04-01T10:33:44.677Z"),
	"activityId" : "cd2eedb7-ff7e-4e7b-9f9b-495a392bc467",
	"userId" : "26",


I'm not sure there is a way in Biocollect to prevent a user from reporting twice the same route. Right ?

I don't know how to deal with that one, since the numbers (Pärluggla at p10, x1) and the comments are a bit different.


**09FSV-1-2022**
1)
	"activityId" : "043a2cbb-7cc9-bafb-b839-127fe4607605",
	"dateCreated" : ISODate("2023-01-11T13:56:19Z"),
	"lastUpdated" : ISODate("2023-01-11T13:56:19Z"),
	"excelFile" : "09FSV-1 2022.xlsx"
2)
	"activityId" : "f7b10cda-e75d-b5cf-0d49-944a37ad7e73",
	"dateCreated" : ISODate("2023-01-11T13:56:19Z"),
	"lastUpdated" : ISODate("2023-01-11T13:56:19Z"),
	"excelFile" : "09FSV-2 2022.xlsx"

so we have 2 different files, leading to the same site-period-year 
problem is in the second file : 
![Screenshot from 2023-03-07 08-49-53](https://user-images.githubusercontent.com/50901365/223358159-d618e561-d520-455a-934f-fd98554f654a.png)
period 2 in the name, period 1 in the file. The script is supposed to complain when the data in the name is different than in the file. Maybe it's not the case for the period, since it's a specificity of the nattrutter. To be checked.

SInce there is no other 09FSV-2 2022 in the database, i think we just have to change this period number to 2 instead of 1 (for "activityId" : "f7b10cda-e75d-b5cf-0d49-944a37ad7e73") and we're good, right ?

**Comment by ekol-ali** [comment]
Thanks!

04ENO - your removal is OK

18GSO - just leave it for the moment, **I will contact the surveyor**
RE: Entering a route twice in BioCollect. I thought it would be impossible, but apparently not. Can it be arranged? Something like "Varning: du har redan rapporterat data för denna rutt, denna period och år. Vill du göra en ändring måste du kontakta oss på Svensk Fågeltaxering". But I can see this is not easy to solve..... One could at least have this once they try to submit a dublon, but prefereably before that.

09FSV - I have now in BioCollect changed the april survey from period 1 to period 2.
RE: Import function. A reasonably effective filter could be to check positions 5 and 6 in date (2022**04**17) and see that Period matches this. 03 = 1, 04 = 2, 06 = 3. Another possibility is to run, at some pre-determined time, the search you just did, for dublons. Something that could be seen in Monitoring dashboard?

**Comment by mathieuLU** [comment]
about the possibility to report twice for the same route/period
=> does not exist in BioCollect right now. Possible to do it, but could take time. Not sure it's worth it.

import function :
there is now a couple of new tests for nattrutter excel files : 
 - check if the period in the filename and in the file (cell L13) are the same
 - check if the period is one of these : "03 = 1, 04 = 2, 06 = 3"
if not, file refused

and yes we could add a quality check in the dashboard to get the doublons. Could be done for all schemes actually

**Comment by ekol-ali** [comment]
If double reporting is difficult to prevent - leave it for now. I guess it rarely happens. The current double reporting was triggered by Martin asking the surveyor to report missing surveyes (period 2 and 3) and she apparently forgot she already reported period 1.

Import function:
First test: OK!
Second test: I presume this includes checking the date ("2022**03**13") as I suggested?

Quality checks in dashboard, for all schemes: 
I think it would be really good! It would hopefully convince MG that this is a good "page" to look into now and then. Could it even be conencted to an "alarm mail" to fageltaxering@biol.lu.se? Then errors could be corrected immedately, especially important for reports coming through BioCollect.

**Comment by mathieuLU** [comment]
yes the test follows what you suggested with the date.

and i add the duplicate check to the dashboard todo list
